"""initial db scripts

Revision ID: 2ec14e5e9cb7
Revises: 
Create Date: 2023-07-31 17:21:15.263464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec14e5e9cb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fib_series',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fib_series')
    # ### end Alembic commands ###
